### PR TITLE
Complete module rework

### PR DESCRIPTION
**Pull request by stylemistake**
This is a bulk of my recent rework of this module.

It was rewritten to be especially compliant to the Domreg EPP spec, and handles some situations better than the old module. Non-exhaustive list of features:

- Built with PHP 7.0 featureset in mind
- Proper session handshake and packet validation
- More efficient use of Domreg API
- Better handling of nameserver groups
- Actually working `poll`, which has a high level API in form of `$domreg->retrieveMessages(function ($msg))`

@tomsim @kareiva - Highlighting you guys to check if it works for you, and if you are able, incorporate `orgcode` changes into this branch. It will soon become master.

I hope you like the new code architecture, and especially, EPP request building and parsing. If you have comments, please provide.

P.S. This exact code was tested and is currently in production in happyhosting.lt

### CODE REVIEW

**Comment by tomsim** [comment]
I suggest to make new branch let say version 2. O better do new project.

**Comment by stylemistake** [comment]
My only question is - why? Are there any problems with it?

**Comment by tomsim** [comment]
I not tested yet. I think all will be fine.

**Comment by stylemistake** [comment]
This branch is getting production ready. If nobody has any comments (@tomsim), this will become a new master on March 1st.

Cheers!

**Pull request merged**
