### PR TITLE
Implement orgcode.

### PR DESCRIPTION
**Pull request by tomsim**

### CODE REVIEW

**Comment by kareiva** [comment]
@tomsim mind fixing up the commit messages?

**Comment by tomsim** [comment]
@kareiva what do mean? You do not like that there are to commits with same message?

**Comment by kareiva** [comment]
I mean squashing up the two identical commits, correcting language (punctuation) and if possible, providing some documentation references to orgcode. 

Otherwise, LGTM. @stylemistake any comments?

**Comment by tomsim** [comment]
@kareiva now OK?

**Comment by stylemistake** [comment]
@kareiva LGTM, except that I have a newer codebase which was never pushed here. I will make a separate PR.

**Pull request merged**
